refactor: normalize common options for all parsers
expressjs/body-parser pull request #551
Opened 2024-10-22 21:11 UTC by Phillip9587

Based on #550 

This PR introduces the `normalizeOptions` function, which standardizes and validates common parser options like `inflate`, `limit`, `type`, and `verify`. It ensures consistent defaults and removes duplication across the parsers.

2024-11-14 17:16 UTC, wesleytodd commented
How much of this would also overlap with @ctcpip's attempt to revive #544? Would we be better off talking that approach to simplification?

2025-02-17 19:10 UTC, jonchurch requested changes
it LGTM, but with the one nit I left so marking as request for change. The nit doesn't have to block, but I think it's a sane addition.

2025-02-17 19:10 UTC, jonchurch commented on lib/utils.js
> +function normalizeOptions (options, defaultType) {
We could throw if `defaultType` is not provided

Previously it was implicitly required in that all parsers defined a fallback, but the current approach will accept undefined here silently and make the parser match against any Content-Type header provided in a req. It's unlikely that is expected or desired behavior on the part of a maintainer creating a new parser.

I put it up top because we are verifying internal use here, not the normalized value after considering the user input.

```suggestion
function normalizeOptions (options, defaultType) {
  if (!defaultType) {
    // Parsers must define a default content type or function
    throw new TypeError('defaultType must be provided')
  }
```

2025-02-18 07:49 UTC, Phillip9587 commented
@jonchurch I've made the requested changes. I think we should merge this first as foundational work for #22, so that when we start on it, the necessary changes are already in place and the scope remains smaller. Let me know what you think!

2025-02-18 14:21 UTC, bjohansebas commented on lib/utils.js
> + * Copyright(c) 2014-2015 Douglas Christopher Wilson
It's a new file, so it would be better to omit this or add that it should be express contributors.

2025-02-18 14:29 UTC, bjohansebas commented on lib/utils.js
> +function normalizeOptions (options, defaultType) {
You probably want to add tests to check its behavior at the function level

2025-02-18 16:18 UTC, Phillip9587 commented on lib/utils.js
> + * Copyright(c) 2014-2015 Douglas Christopher Wilson
Should I remove the header completely?

2025-02-18 17:42 UTC, bjohansebas commented on lib/utils.js
> + * Copyright(c) 2014-2015 Douglas Christopher Wilson
Probably this is the correct header only for this file, since we have to respect copyright rights. This happened on the website and the following copyright was added

```suggestion
 * Copyright(c) Express Contributors
```

2025-02-18 20:19 UTC, bjohansebas approved these changes
LGTM

2025-02-19 18:31 UTC, jonchurch requested changes

2025-02-19 18:53 UTC, jonchurch commented on lib/utils.js
> +  }
Woops, I missed something else here. 

User facing `type` option should ahve the signature of `string | string[] | function`

This is getting complicated for `defaultType` so Im going to back track here and resolve the comment.

We don't need to worry rn about validating the internal use, I just wanted to catch anyone who accidentally forgot to pass a `defaultType` when creating a new parser.

2025-02-19 18:54 UTC, jonchurch commented on test/utils.js
> +})
backtracking here and marking as resolved, will suggest the functionality check in another comment

2025-02-19 19:13 UTC, jonchurch requested changes

2025-02-19 19:13 UTC, jonchurch commented on lib/utils.js
> +  if (!defaultType || typeof defaultType !== 'string') {
Lets keep this simpler for now and just validate that defaultType is defined
```suggestion
  if (!defaultType) {
```

2025-02-19 19:13 UTC, jonchurch commented on lib/utils.js
> + * @param {string} defaultType default content type
```suggestion
 * @param {string | string[] | function} defaultType default content type(s) or a function to determine it
```

2025-02-19 19:13 UTC, jonchurch commented on test/utils.js
> +})
Added a test under describe type to test usage w/ array of strings
Removed the "should throw an error if defaultType not a string" test.

added two tests to  assert on the functionality of defaultType when provided as string, array of strings, or function

```suggestion
    describe('type', () => {
      it('should return the default type if type is not provided', () => {
        const result = normalizeOptions({}, 'application/json')
        assert.strictEqual(result.shouldParse({ headers: { 'content-type': 'application/json', 'content-length': '1024' } }), true)
        assert.strictEqual(result.shouldParse({ headers: { 'content-type': 'application/xml', 'content-length': '1024' } }), false)
      })

      it('should accept a string type', () => {
        const result = normalizeOptions({ type: 'application/xml' }, 'application/json')
        assert.strictEqual(result.shouldParse({ headers: { 'content-type': 'application/xml', 'content-length': '1024' } }), true)
        assert.strictEqual(result.shouldParse({ headers: { 'content-type': 'application/json', 'content-length': '1024' } }), false)
      })

      it('should accept an array of strings type', () => {
        const result = normalizeOptions({ type: ['application/xml', 'application/*+json'] }, 'application/json')
        assert.strictEqual(result.shouldParse({ headers: { 'content-type': 'application/xml', 'content-length': '1024' } }), true)
        assert.strictEqual(result.shouldParse({ headers: { 'content-type': 'application/ld+json', 'content-length': '1024' } }), true)
        assert.strictEqual(result.shouldParse({ headers: { 'content-type': 'application/json', 'content-length': '1024' } }), false)
      })

      it('should accept a type checking function', () => {
        const result = normalizeOptions({ type: () => true }, 'application/json')
        assert.strictEqual(result.shouldParse({ headers: { 'content-type': 'application/xml' } }), true)
        assert.strictEqual(result.shouldParse({ headers: { 'content-type': 'application/json' } }), true)
      })
    })
  })

  describe('defaultType', () => {
    it('should throw an error if defaultType is not provided', () => {
      assert.throws(() => {
        normalizeOptions({})
      }, /defaultType must be provided/)
      assert.throws(() => {
        normalizeOptions({}, undefined)
      }, /defaultType must be provided/)
    })

    it('should convert string defaultType to a request content-type checking function', () => {
      const result = normalizeOptions({}, 'application/json')
      assert.strictEqual(typeof result.shouldParse, 'function')
      assert.strictEqual(result.shouldParse({ headers: { 'content-type': 'application/json', 'content-length': '1024' } }), true)
      assert.strictEqual(result.shouldParse({ headers: { 'content-type': 'application/xml', 'content-length': '100' } }), false)
    })

    it('should convert string defaultType to a request content-type checking function', () => {
      const result = normalizeOptions({}, 'application/json')
      assert.strictEqual(typeof result.shouldParse, 'function')
      assert.strictEqual(result.shouldParse({ headers: { 'content-type': 'application/json', 'content-length': '1024' } }), true)
      assert.strictEqual(result.shouldParse({ headers: { 'content-type': 'application/xml', 'content-length': '100' } }), false)
    })

    it('should use function defaultType directly as the request content-type checker', () => {
      const typeFunction = (req) => req.headers['content-type'].endsWith('+json')
      const result = normalizeOptions({}, typeFunction)
      assert.strictEqual(result.shouldParse, typeFunction)
      assert.strictEqual(result.shouldParse({ headers: { 'content-type': 'application/ld+json' } }), true)
      assert.strictEqual(result.shouldParse({ headers: { 'content-type': 'application/xml' } }), false)
    })
  })
})
```

2025-02-19 21:19 UTC, Phillip9587 commented on lib/utils.js
> + */
I think that the type should be just `string | string[]` here. If a function is passed as `type` oder `defaultType` we just call that function and don't need the default type-checker

2025-02-19 23:44 UTC, jonchurch approved these changes

2025-03-05 15:49 UTC, Phillip9587 commented
Hey everyone, I just wanted to follow up on this PR and see if there's anything I can do to help move it forward. Let me know if any changes or additional context are needed! Thanks!

2025-03-11 06:58 UTC, Phillip9587 commented
Hey @jonchurch, thanks again for your review and approval a few weeks ago! I just wanted to check in and see if it’s all right to go ahead and merge this. Let me know if you have any additional concerns.

2025-03-23 22:18 UTC, UlisesGascon commented
Is this a semver minor, right?

2025-03-23 23:06 UTC, bjohansebas commented
I would say it's a patch, this change doesn't introduce any new functionality, it just refactors it.

2025-03-23 23:07 UTC, bjohansebas approved these changes

2025-03-24 11:28 UTC, UlisesGascon approved these changes

2025-03-24 15:34 UTC, bjohansebas approved these changes

2025-03-26 14:12 UTC, Phillip9587 commented
@UlisesGascon Can we merge this now?

2025-03-26 14:21 UTC, UlisesGascon commented
I am checking with @wesleytodd... So far the plan is to include it in the next release (that will be shipped to in Express 5.1.0) :)

2025-03-26 14:29 UTC, Phillip9587 commented
@UlisesGascon Thanks! My work on #22 depends on this, so I'd really appreciate it if it could be merged soon.

2025-03-26 21:34 UTC, merged